# Generated by Django 5.0.9 on 2024-10-10 13:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('uploadfilesapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='pan_card_pic_blob',
            field=models.BinaryField(blank=True, null=True),
        ),
    ]
