# Generated by Django 5.1 on 2024-09-02 18:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Authors',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('AuthorName', models.CharField(max_length=100)),
                ('Country', models.CharField(max_length=100)),
                ('BookName', models.CharField(max_length=100)),
            ],
        ),
    ]
