# Generated by Django 5.0.9 on 2024-09-11 10:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('FirstName', models.CharField(max_length=100)),
                ('LastName', models.CharField(max_length=100)),
                ('TitleName', models.CharField(max_length=100)),
                ('HasPassport', models.BooleanField()),
                ('Salary', models.IntegerField()),
                ('BirthDate', models.DateField()),
                ('HireDate', models.DateField()),
                ('Notes', models.CharField(max_length=200)),
                ('Country', models.CharField(choices=[('BAN', 'Bangladesh'), ('USA', 'United States'), ('UK', 'United Kingdom'), ('CAN', 'Canada'), ('AUS', 'Australia'), ('JPN', 'Japan')], default=None, max_length=100)),
            ],
        ),
    ]
