# Generated by Django 5.0.9 on 2024-09-15 11:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PayRollApp', '0005_remove_employee_country_employee_empcountry_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='EmpCountry',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.PROTECT, related_name='Countries', to='PayRollApp.country'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='EmpDepartment',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.PROTECT, related_name='Departments', to='PayRollApp.department'),
        ),
    ]
