# Generated by Django 5.0.9 on 2024-09-23 12:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PayRollApp', '0007_parttimeemployee'),
    ]

    operations = [
        migrations.CreateModel(
            name='City',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='State',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, null=True)),
                ('country', models.ForeignKey(default=None, on_delete=django.db.models.deletion.PROTECT, to='PayRollApp.country')),
            ],
        ),
        migrations.CreateModel(
            name='OnSiteEmployees',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=30, null=True)),
                ('last_name', models.CharField(max_length=30, null=True)),
                ('city', models.ForeignKey(default=None, on_delete=django.db.models.deletion.PROTECT, to='PayRollApp.city')),
                ('country', models.ForeignKey(default=None, on_delete=django.db.models.deletion.PROTECT, to='PayRollApp.country')),
                ('state', models.ForeignKey(default=None, on_delete=django.db.models.deletion.PROTECT, to='PayRollApp.state')),
            ],
        ),
        migrations.AddField(
            model_name='city',
            name='state',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.PROTECT, to='PayRollApp.state'),
        ),
    ]
