# Generated by Django 4.2.10 on 2024-08-14 09:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CarSpecs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('car_brand', models.CharField(max_length=255)),
                ('car_model', models.CharField(max_length=255)),
                ('production_year', models.CharField(max_length=255)),
                ('car_body', models.CharField(max_length=255)),
                ('engine_type', models.CharField(max_length=255)),
            ],
        ),
    ]
