# Generated by Django 4.2.10 on 2024-04-15 09:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('enroll', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='blog',
            old_name='description',
            new_name='desc',
        ),
    ]
