# Generated by Django 4.2.10 on 2024-03-19 19:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0004_alter_post_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='other',
            field=models.FileField(blank=True, null=True, upload_to='posts/media/uploads/'),
        ),
    ]
