# Generated by Django 4.2.10 on 2024-03-19 20:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0005_post_other'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='other',
        ),
    ]
